# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Push CPU Binary Nightly

on: [push, pull_request]
  # run every day at 11:15am
  # schedule:
    # - cron:  '15 11 * * *'
  # or manually trigger it
  # workflow_dispatch:

jobs:

  # build, test and upload on cpu hosts
  build_test_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - macos-latest
          - ubuntu-latest
          # - windows-latest
        python-version:
          - 3.7
          - 3.8
          - 3.9
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Check ldd --version
      run: ldd --version
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    # Update references
    # TODO: update the git submodule sync after we fixed the auto-sync part
    - name: Git submodule update
      run: |
        git submodule init
        git submodule update --remote --recursive
        cd third_party/fbgemm/
        git submodule sync
        git submodule update --init --recursive
        git log
    - name: Update pip
      run: |
        sudo yum update -y
        sudo yum -y install git python3-pip
        sudo pip3 install --upgrade pip
    - name: Setup conda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
        bash ~/miniconda.sh -b -p $HOME/miniconda
    - name: Setup path
      run: |
        echo "/home/ec2-user/miniconda/bin" >> $GITHUB_PATH
        echo "CONDA=/home/ec2-user/miniconda" >> $GITHUB_PATH
    - name: Create conda env
      run: |
        conda create --name build_binary python=${{ matrix.python-version }}
        conda info
    - name: Check python version no conda
      run: |
        python --version
    - name: Check python version
      run: |
        conda run -n build_binary python --version
    - name: Install gcc
      shell: bash
      run: |
        sudo yum group install -y "Development Tools"
    - name: setup Path
      run: |
        echo /usr/local/bin >> $GITHUB_PATH
    - name: Install PyTorch
      shell: bash
      run: |
        conda run -n build_binary python -m pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
    - name: Install dependencies
      shell: bash
      run: |
        conda run -n build_binary python -m pip install -r requirements.txt
    - name: Test Installation of dependencies
      run: |
        conda run -n build_binary python -c "import torch.distributed"
        echo "torch.distributed succeeded"
        conda run -n build_binary python -c "import skbuild"
        echo "skbuild succeeded"
        conda run -n build_binary python -c "import numpy"
        echo "numpy succeeded"
    # for the conda run with quotes, we have to use "\" and double quotes
    # here is the issue: https://github.com/conda/conda/issues/10972
    - name: Build maskedtensor nightly
      run: |
        rm -r dist || true
        conda run -n build_binary \
          python setup.py bdist_wheel \
          --package_name maskedtensor-nightly-cpu \
          --cpu_only \
          --python-tag=${{ matrix.python-tag }}
    - name: Upload wheel as GHA artifact
      uses: actions/upload-artifact@v2
      with:
        name: maskedtensor_nightly_${{ matrix.python-version }}_${{ matrix.cuda-tag }}.whl
        path: dist/maskedtensor_nightly*.whl
    - name: Install maskedtensor nightly
      run: |
        conda run -n build_binary python -m pip install dist/maskedtensor_nightly*.whl
    - name: Test maskedtensor installation
      shell: bash
      run: |
        conda run -n build_binary \
          python -c "import maskedtensor"
    # Push to Pypi
    - name: Push TorchRec Binary to PYPI
      env:
          PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
      run: |
        conda run -n build_binary python -m pip install twine
        conda run -n build_binary --repository testpypi \
          python -m twine upload \
            --username __token__ \
            --password "$PYPI_TOKEN" \
            dist/maskedtensor_nightly*.whl
